# Generated by Django 5.2.1 on 2025-05-31 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0002_feedback_pet_remove_contactmessage_sent_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='created_at',
        ),
    ]
