# Generated by Django 5.2.1 on 2025-05-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0003_remove_contactmessage_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='pet_type',
        ),
        migrations.AddField(
            model_name='pet',
            name='adopted',
            field=models.BooleanField(default=False, verbose_name='Пристроен'),
        ),
        migrations.AddField(
            model_name='pet',
            name='sterilized',
            field=models.BooleanField(default=False, verbose_name='Стерилизован'),
        ),
        migrations.AddField(
            model_name='pet',
            name='type',
            field=models.CharField(choices=[('cat', 'Кошка'), ('dog', 'Собака')], default='cat', max_length=10, verbose_name='Вид'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='vaccinated',
            field=models.BooleanField(default=False, verbose_name='Привит'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.PositiveIntegerField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='description',
            field=models.TextField(blank=True, verbose_name='История'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pet_photos/', verbose_name='Фото'),
        ),
    ]
