# Generated by Django 5.2.1 on 2025-05-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0004_remove_pet_date_added_remove_pet_pet_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('male', 'Мальчик'), ('female', 'Девочка')], default='male', max_length=10, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, default='male', upload_to='pet_photos/', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
