# Generated by Django 5.2.1 on 2025-05-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0005_pet_gender_alter_pet_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='age',
        ),
        migrations.AddField(
            model_name='pet',
            name='age_months',
            field=models.PositiveIntegerField(default=0, verbose_name='Возраст в месяцах'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('male', 'Мальчик'), ('female', 'Девочка')], max_length=6, verbose_name='Пол'),
        ),
    ]
