# Generated by Django 5.2.1 on 2025-06-02 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0007_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date'], 'verbose_name': 'new', 'verbose_name_plural': 'news'},
        ),
    ]
