# Generated by Django 5.2.1 on 2026-04-17 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0010_userprofile_delete_contactmessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('housing_type', models.CharField(max_length=100, verbose_name='Тип жилья')),
                ('has_other_pets', models.BooleanField(default=False, verbose_name='Есть другие животные')),
                ('has_children', models.BooleanField(default=False, verbose_name='Есть дети')),
                ('experience', models.TextField(blank=True, verbose_name='Опыт содержания животных')),
                ('why_adopt', models.TextField(verbose_name='Почему хотите взять животное')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('review', 'На рассмотрении'), ('approved', 'Одобрена'), ('rejected', 'Отклонена'), ('meeting', 'Назначено знакомство')], default='new', max_length=20, verbose_name='Статус')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='shelter.pet', verbose_name='Питомец')),
            ],
            options={
                'verbose_name': 'Заявка на усыновление',
                'verbose_name_plural': 'Заявки на усыновление',
                'ordering': ['-created_at'],
            },
        ),
    ]
