# Generated by Django 5.2.1 on 2026-04-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0011_adoptionapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionapplication',
            name='admin_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий администратора'),
        ),
    ]
