# Generated by Django 5.2.1 on 2026-04-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0012_adoptionapplication_admin_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('housing_type', models.CharField(choices=[('apartment', 'Квартира'), ('house', 'Частный дом'), ('rented', 'Съёмное жильё')], max_length=20, verbose_name='Тип жилья')),
                ('has_children', models.BooleanField(default=False, verbose_name='Есть дети')),
                ('has_other_pets', models.BooleanField(default=False, verbose_name='Есть другие животные')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Опыт содержания животных (лет)')),
                ('activity_level', models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая')], max_length=20, verbose_name='Уровень активности')),
                ('time_at_home', models.CharField(choices=[('rarely', 'Редко бываю дома'), ('often', 'Часто бываю дома'), ('always', 'Почти всегда дома')], max_length=20, verbose_name='Сколько времени проводите дома')),
                ('pet_preference', models.CharField(choices=[('cat', 'Кошка'), ('dog', 'Собака'), ('any', 'Не важно')], default='any', max_length=10, verbose_name='Предпочтение по типу животного')),
                ('additional_info', models.TextField(blank=True, verbose_name='Дополнительная информация')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заполнения')),
            ],
            options={
                'verbose_name': 'Анкета будущего хозяина',
                'verbose_name_plural': 'Анкеты будущих хозяев',
                'ordering': ['-created_at'],
            },
        ),
    ]
