# Generated by Django 5.2.1 on 2026-04-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0013_ownerquestionnaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='activity_level',
            field=models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая')], default='medium', max_length=20, verbose_name='Уровень активности'),
        ),
        migrations.AddField(
            model_name='pet',
            name='can_live_with_children',
            field=models.BooleanField(default=True, verbose_name='Можно в семью с детьми'),
        ),
        migrations.AddField(
            model_name='pet',
            name='can_live_with_other_pets',
            field=models.BooleanField(default=True, verbose_name='Можно с другими животными'),
        ),
        migrations.AddField(
            model_name='pet',
            name='requires_experience',
            field=models.BooleanField(default=False, verbose_name='Требуется опытный хозяин'),
        ),
        migrations.AddField(
            model_name='pet',
            name='suitable_for_apartment',
            field=models.BooleanField(default=True, verbose_name='Подходит для квартиры'),
        ),
    ]
