# Generated by Django 5.2.1 on 2026-04-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0014_pet_activity_level_pet_can_live_with_children_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerquestionnaire',
            name='adoption_goal',
            field=models.CharField(choices=[('companion', 'Компаньон'), ('family', 'Для семьи'), ('active_walks', 'Для активных прогулок'), ('any', 'Не важно')], default='any', max_length=20, verbose_name='Цель усыновления'),
        ),
        migrations.AddField(
            model_name='ownerquestionnaire',
            name='pet_age_preference',
            field=models.CharField(choices=[('young', 'Молодой'), ('adult', 'Взрослый'), ('any', 'Не важно')], default='any', max_length=10, verbose_name='Предпочтительный возраст питомца'),
        ),
        migrations.AddField(
            model_name='ownerquestionnaire',
            name='pet_gender_preference',
            field=models.CharField(choices=[('male', 'Мальчик'), ('female', 'Девочка'), ('any', 'Не важно')], default='any', max_length=10, verbose_name='Предпочтительный пол питомца'),
        ),
        migrations.AddField(
            model_name='ownerquestionnaire',
            name='ready_for_medical_care',
            field=models.BooleanField(default=False, verbose_name='Готов(а) ухаживать за питомцем с особенностями здоровья'),
        ),
        migrations.AddField(
            model_name='pet',
            name='age_group',
            field=models.CharField(choices=[('young', 'Молодой'), ('adult', 'Взрослый')], default='adult', max_length=10, verbose_name='Возрастная группа'),
        ),
        migrations.AddField(
            model_name='pet',
            name='can_stay_alone',
            field=models.BooleanField(default=True, verbose_name='Может оставаться один'),
        ),
        migrations.AddField(
            model_name='pet',
            name='health_status',
            field=models.CharField(choices=[('healthy', 'Здоров'), ('care_needed', 'Нужен особый уход')], default='healthy', max_length=20, verbose_name='Состояние здоровья'),
        ),
        migrations.AddField(
            model_name='pet',
            name='temperament',
            field=models.CharField(choices=[('calm', 'Спокойный'), ('active', 'Активный'), ('friendly', 'Дружелюбный'), ('careful', 'Осторожный')], default='friendly', max_length=20, verbose_name='Характер'),
        ),
    ]
